### ISSUE TITLE
Cron job initialization

### ISSUE THREAD

**Issue by erikyo** [rocklobster-in/flamingo#102]
It seems that the `wp` action is only executed on the front end of the website (and additionally i believe we don't need to fire an action each page load for that).

https://github.com/takayukister/flamingo/blob/7f9065e8dcb71500f28775116be912f340f32536/includes/cron.php#L9-L20

To give a try just replace the content of `flamingo_schedule_activation` with `die();` then reload the page website and wordpress admin and only the frontend will result into a white page.

Then replace the hook `wp` with `admin_init` and retry (result: white page for admin but not for front facing pages).

**Comment by takayukister** [comment]
Putting aside the question whether using the `wp` action hook here is appropriate or not, apparently the current [common practice](https://core.trac.wordpress.org/browser/tags/6.2.1/src/wp-includes/default-filters.php) is to use the `init` or `admin_init` hook for a schedule activating function. Since Flamingo uses WP cron to move to trash old data that are only seen in the admin area, using `admin_init` feels more natural.
